In [2]:
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA

In [3]:
data = {
    'Study_Hours' : [2,4,6,8,10],
    'Attendance' : [50,60,70,80,90],
    'Marks' : [40,50,60,70,80]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
print("Original Data")
df

Original Data

   Study_Hours  Attendance  Marks
0            2          50     40
1            4          60     50
2            6          70     60
3            8          80     70
4           10          90     80

In [6]:
normalizer = MinMaxScaler()
normalized_data = normalizer.fit_transform(df)

In [8]:
normalized_df = pd.DataFrame(normalized_data,columns = df.columns)

In [10]:
print("Normalized Data")
normalized_df.round(2)

Normalized Data

   Study_Hours  Attendance  Marks
0         0.00        0.00   0.00
1         0.25        0.25   0.25
2         0.50        0.50   0.50
3         0.75        0.75   0.75
4         1.00        1.00   1.00

In [6]:
standardrizer = StandardScaler()
standardrized_data = standardrizer.fit_transform(df)

In [7]:
standardrized_df = pd.DataFrame(standardrized_data,columns = df.columns)

In [8]:
print("Standardrized Data")
standardrized_df.round(2)

Standardrized Data

   Study_Hours  Attendance  Marks
0        -1.41       -1.41  -1.41
1        -0.71       -0.71  -0.71
2         0.00        0.00   0.00
3         0.71        0.71   0.71
4         1.41        1.41   1.41

In [5]:
pca = PCA(n_components=2)

In [9]:
pca_data = pca.fit_transform(standardrized_data)

In [10]:
pca_df = pd.DataFrame(pca_data,columns = ["PC1","PC2"])

In [13]:
print("Data after PCA")
pca_df.round(2)

Data after PCA

    PC1  PC2
0 -2.45 -0.0
1 -1.22  0.0
2  0.00  0.0
3  1.22 -0.0
4  2.45 -0.0